version: '3'

services:
  php:
    container_name: sql_injection_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./html:/var/www/html
    ports:
      - 8000:80

  mysql:
    container_name: sql_injection_mysql
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
